modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/LCLPYT/Core/issues"
displayURL="https://github.com/LCLPYT/Core"
authors="LCLP"
license="MIT"

[[mods]]
    modId="core"
    version="${version}"
    displayName="Core"
    updateJSONURL="https://raw.githubusercontent.com/LCLPYT/Core/master/Core/update.json"
    logoFile="logo.png"
    credits="LCLPNetwork!"
    description='''
    Internal Server mod.
    '''
    
    [[dependencies.core]]
        modId="corebase"
        mandatory=true
        versionRange="[1.4,)"
        ordering="BEFORE"
        side="SERVER"
    [[dependencies.core]]
        modId="forge"
        mandatory=true
        versionRange="[34,)"
        ordering="NONE"
        side="SERVER"
    [[dependencies.core]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.3]"
        ordering="NONE"
        side="BOTH"
